### ISSUE TITLE
No highlighting

### ISSUE THREAD

**Issue by BorisKourt** [zyedidia/literate.vim#1]
I have installed this plugin via Vundle, and `lit` is in my path. Currently there is no syntax highlighting available, even for `@code_type` and other Literate specific tags. 

I have disabled all other plugins, without any luck. 

Do I need to manually set `.lit` to use your syntax in `.vimrc`?

Thank you for putting this togther. 

(As an aside `<C-]>` seems to conflict with Ctags.)

---

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 24 2014 14:12:07)
```

System: OSX

**Comment by zyedidia** [comment]
Hmm, I tried reinstalling and didn't have any problems.

Make sure that you have

``` vimL
Plugin 'zyedidia/literate.vim'
```

in your `.vimrc` and not

``` vimL
Plugin 'zyedidia/literate'
```

and also that you've enabled syntax with `syntax on`.

---

About `<C-]>` I'll add some way to remap that. If you have any suggestions for a better default I'd be happy to hear what you think (maybe `<C-t>`?).

**Comment by BorisKourt** [comment]
> `Plugin 'zyedidia/literate.vim'` and not `Plugin 'zyedidia/literate'`

Yup that was the issue. Silly me! Thanks for your prompt response. 

As for the keybinding, I am actually not sure. I don't use vim enough to make a good suggestion.
